src/main/java/lab/s2jh/aud/entity/LoggingEvent.java
package lab.s2jh.aud.entity;

import java.util.Date;
import java.util.List;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import lab.s2jh.core.annotation.MetaData;
import lab.s2jh.core.entity.PersistableEntity;
import lab.s2jh.core.web.json.DateTimeJsonSerializer;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;

import org.apache.commons.lang3.StringUtils;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.GenericGenerator;
import org.springframework.util.CollectionUtils;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/** 
 * 基于logback的DBAppender表结构规范对应的实体定义
 * @see http://logback.qos.ch/manual/configuration.html#DBAppender
 */
@Getter
@Setter
@Accessors(chain = true)
@Access(AccessType.FIELD)
@Entity
@Table(name = "logging_event")
@Cache(usage = CacheConcurrencyStrategy.NONE)
@MetaData(value = "日志事件", comments = "用于基于Logback日志DBAppender的ERROR日志数据存取")
public class LoggingEvent extends PersistableEntity<Long> {

    private static final long serialVersionUID = 3807617732053699145L;

    @Id
    @Column(name = "event_id")
    @GeneratedValue(generator = "idGenerator")
    @GenericGenerator(name = "idGenerator", strategy = "native")
    private Long id;

    private Long timestmp;

    @Column(name = "formatted_message", length = 4000)
    private String formattedMessage;

    @Column(name = "logger_name", length = 256)
    private String loggerName;

    @Column(name = "level_string", length = 256)
    private String levelString;

    @Column(name = "thread_name", length = 256)
    private String threadName;

    @Column(name = "reference_flag", length = 256)
    private Integer referenceFlag;

    private String arg0;
    private String arg1;
    private String arg2;
    private String arg3;

    @Column(name = "caller_filename", length = 256)
    private String callerFilename;

    @Column(name = "caller_class", length = 256)
    private String callerClass;

    @Column(name = "caller_method", length = 256)
    private String callerMethod;

    @Column(name = "caller_line", length = 256)
    private String callerLine;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "loggingEvent", cascade = CascadeType.ALL, orphanRemoval = true)
    @JsonIgnore
    private List<LoggingEventProperty> loggingEventProperties;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "loggingEvent", cascade = CascadeType.ALL, orphanRemoval = true)
    @JsonIgnore
    private List<LoggingEventException> loggingEventExceptions;

    @Enumerated(EnumType.STRING)
    @Column(length = 32, nullable = true)
    private LoggingHandleStateEnum state = LoggingHandleStateEnum.TODO;

    @Column(length = 4000)
    @JsonIgnore
    private String operationExplain;

    public static enum LoggingHandleStateEnum {

        @MetaData("已修正")
        FIXED,

        @MetaData("待处理")
        TODO,

        @MetaData("已忽略")
        IGNORE;
    }

    @Transient
    @JsonSerialize(using = DateTimeJsonSerializer.class)
    public Date getTimestampDate() {
        return new Date(this.getTimestmp());
    }

    @Transient
    @JsonIgnore
    public String getExceptionStack() {
        StringBuilder sb = new StringBuilder();
        if (!CollectionUtils.isEmpty(loggingEventExceptions)) {
            for (LoggingEventException loggingEventException : loggingEventExceptions) {
                sb.append(loggingEventException.getTraceLine() + "\n");
            }
        }
        return sb.toString();
    }

    @Override
    @Transient
    public String getDisplay() {
        return StringUtils.substring(formattedMessage, 0, 50);
    }

}

src/main/java/lab/s2jh/module/schedule/BaseQuartzJobBean.java
package lab.s2jh.module.schedule;

import java.util.Map;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;

import lab.s2jh.core.exception.ServiceException;
import lab.s2jh.module.schedule.entity.JobBeanCfg;
import lab.s2jh.module.schedule.service.JobBeanCfgService;
import lab.s2jh.support.service.FreemarkerService;

import org.apache.commons.lang3.StringUtils;
import org.quartz.JobExecutionContext;
import org.quartz.JobExecutionException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.jpa.EntityManagerFactoryUtils;
import org.springframework.orm.jpa.EntityManagerHolder;
import org.springframework.scheduling.quartz.QuartzJobBean;
import org.springframework.transaction.support.TransactionSynchronizationManager;
import org.springframework.web.context.support.SpringBeanAutowiringSupport;

/**
 * 自定义Quartz Job业务对象的基类定义
 * 业务Job继承此抽象基类，获得Spring ApplicationContext的能力从而可以获取Spring声明的Bean对象
 * 同时实现QuartzJobBean约定接口，编写定时处理逻辑
 */
public abstract class BaseQuartzJobBean extends QuartzJobBean {

    private static Logger logger = LoggerFactory.getLogger(BaseQuartzJobBean.class);

    @Autowired
    private EntityManagerFactory entityManagerFactory;

    @Autowired
    private JobBeanCfgService jobBeanCfgService;

    @Autowired
    private FreemarkerService freemarkerService;

    /**
     * 基于Freemarker组装任务结果数据文本
     * @param context
     * @param dataMap
     * @return
     */
    protected String buildJobResultByTemplate(JobExecutionContext context, Map<String, Object> dataMap) {
        JobBeanCfg jobBeanCfg = jobBeanCfgService.findByJobClass(context.getJobDetail().getJobClass().getName());
        if (jobBeanCfg != null) {
            String resultTemplate = jobBeanCfg.getResultTemplate();
            if (StringUtils.isNotBlank(resultTemplate)) {
                String result = freemarkerService.processTemplate(jobBeanCfg.getJobClass(), jobBeanCfg.getVersion(), resultTemplate, dataMap);
                return result;
            }
        }
        return "UNDEFINED";
    }

    @Override
    public void executeInternal(JobExecutionContext context) throws JobExecutionException {
        try {
            logger.debug("Invoking executeInternalBiz for {}", this.getClass());

            // Process @Autowired injection for the given target object, based on the current web application context. 
            SpringBeanAutowiringSupport.processInjectionBasedOnCurrentContext(this);

            //绑定JPA Session到当前线程
            if (!TransactionSynchronizationManager.hasResource(entityManagerFactory)) {
                EntityManager entityManager = entityManagerFactory.createEntityManager();
                TransactionSynchronizationManager.bindResource(entityManagerFactory, new EntityManagerHolder(entityManager));
            }

            String result = executeInternalBiz(context);

            //解绑JPA Session从当前线程
            EntityManagerHolder emHolder = (EntityManagerHolder) TransactionSynchronizationManager.unbindResource(entityManagerFactory);
            EntityManagerFactoryUtils.closeEntityManager(emHolder.getEntityManager());

            if (context != null && StringUtils.isNotBlank(result)) {
                context.setResult(result);
            }
            logger.debug("Job execution result: {}", result);
        } catch (Exception e) {
            logger.error("Quartz job execution error", e);
            throw new ServiceException(e.getMessage(), e);
        }
    }

    /**
     * 定时任务内部逻辑实现，注意整个方法不在事务控制边界，因此如果涉及到多数据更新逻辑注意需要把所有业务逻辑封装到相关Service接口中，然后在此方法中一次性调用确保事务控制
     * @param context
     * @return 组装好的任务记录结果信息，可以调用 buildJobResultByTemplate 方法基于Freemarker模板组装复杂的响应文本信息
     */
    protected abstract String executeInternalBiz(JobExecutionContext context);
}

src/main/java/lab/s2jh/module/schedule/ExtSchedulerFactoryBean.java
package lab.s2jh.module.schedule;

import java.util.List;
import java.util.Map;

import javax.sql.DataSource;

import lab.s2jh.module.schedule.entity.JobBeanCfg;
import lab.s2jh.module.schedule.service.JobBeanCfgService;

import org.apache.commons.lang3.reflect.FieldUtils;
import org.quartz.JobDetail;
import org.quartz.SchedulerException;
import org.quartz.Trigger;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.BeansException;
import org.springframework.beans.factory.support.BeanDefinitionBuilder;
import org.springframework.beans.factory.support.DefaultListableBeanFactory;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.scheduling.quartz.CronTriggerFactoryBean;
import org.springframework.scheduling.quartz.JobDetailFactoryBean;
import org.springframework.scheduling.quartz.SchedulerFactoryBean;

import com.google.common.collect.Lists;
import com.google.common.collect.Maps;

/**
 * 扩展标准的SchedulerFactoryBean，实现基于数据库配置的任务管理器初始化
 */
public class ExtSchedulerFactoryBean extends SchedulerFactoryBean {

    private static Logger logger = LoggerFactory.getLogger(ExtSchedulerFactoryBean.class);

    private ConfigurableApplicationContext applicationContext;

    private JobBeanCfgService jobBeanCfgService;

    private boolean runWithinCluster = false;

    public static Map<String, Boolean> TRIGGER_HIST_MAPPING = Maps.newHashMap();

    public void setDataSource(DataSource dataSource) {
        super.setDataSource(dataSource);
        this.runWithinCluster = true;
    }

    public boolean isRunWithinCluster() {
        return runWithinCluster;
    }

    public void setJobBeanCfgService(JobBeanCfgService jobBeanCfgService) {
        this.jobBeanCfgService = jobBeanCfgService;
    }

    public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
        this.applicationContext = (ConfigurableApplicationContext) applicationContext;
        super.setApplicationContext(applicationContext);
    }

    @SuppressWarnings("unchecked")
    @Override
    protected void registerJobsAndTriggers() throws SchedulerException {
        logger.debug("Invoking registerJobsAndTriggers...");
        DefaultListableBeanFactory beanFactory = (DefaultListableBeanFactory) applicationContext.getBeanFactory();
        List<JobBeanCfg> jobBeanCfgs = jobBeanCfgService.findAll();
        List<Trigger> allTriggers = Lists.newArrayList();

        List<Trigger> triggers = null;
        try {
            //基于反射获取已经在XML中定义的triggers集合
            triggers = (List<Trigger>) FieldUtils.readField(this, "triggers", true);
        } catch (IllegalAccessException e) {
            logger.error(e.getMessage(), e);
        }

        if (triggers == null) {
            triggers = Lists.newArrayList();
        } else {
            allTriggers.addAll(triggers);
        }

        for (JobBeanCfg jobBeanCfg : jobBeanCfgs) {
            // 只处理与当前Scheduler集群运行模式匹配的数据
            if (jobBeanCfg.getRunWithinCluster() == null || !jobBeanCfg.getRunWithinCluster().equals(runWithinCluster)) {
                continue;
            }
            // 以任务全类名作为Job和Trigger相关名称
            Class<?> jobClass = null;
            try {
                jobClass = Class.forName(jobBeanCfg.getJobClass());
            } catch (ClassNotFoundException e) {
                //容错处理避免由于配置错误导致无法启动应用
                logger.error(e.getMessage(), e);
            }
            if (jobClass == null) {
                continue;
            }
            String jobName = jobClass.getName();

            boolean jobExists = false;
            for (Trigger trigger : triggers) {
                if (trigger.getJobKey().getName().equals(jobName)) {
                    jobExists = true;
                    break;
                }
            }
            if (jobExists) {
                logger.warn("WARN: Skipped dynamic  job [{}] due to exists static configuration.", jobName);
                continue;
            }

            logger.debug("Build and schedule dynamical job： {}, CRON: {}", jobName, jobBeanCfg.getCronExpression());

            // Spring动态加载Job Bean
            BeanDefinitionBuilder bdbJobDetailBean = BeanDefinitionBuilder.rootBeanDefinition(JobDetailFactoryBean.class);
            bdbJobDetailBean.addPropertyValue("jobClass", jobBeanCfg.getJobClass());
            bdbJobDetailBean.addPropertyValue("durability", true);
            beanFactory.registerBeanDefinition(jobName, bdbJobDetailBean.getBeanDefinition());

            // Spring动态加载Trigger Bean
            String triggerName = jobName + ".Trigger";
            JobDetail jobDetailBean = (JobDetail) beanFactory.getBean(jobName);
            BeanDefinitionBuilder bdbCronTriggerBean = BeanDefinitionBuilder.rootBeanDefinition(CronTriggerFactoryBean.class);
            bdbCronTriggerBean.addPropertyValue("jobDetail", jobDetailBean);
            bdbCronTriggerBean.addPropertyValue("cronExpression", jobBeanCfg.getCronExpression());
            beanFactory.registerBeanDefinition(triggerName, bdbCronTriggerBean.getBeanDefinition());

            allTriggers.add((Trigger) beanFactory.getBean(triggerName));
        }

        this.setTriggers(allTriggers.toArray(new Trigger[] {}));
        super.registerJobsAndTriggers();

        for (Trigger trigger : allTriggers) {
            TRIGGER_HIST_MAPPING.put(trigger.getJobKey().getName(), true);
            for (JobBeanCfg jobBeanCfg : jobBeanCfgs) {
                if (jobBeanCfg.getJobClass().equals(trigger.getJobKey().getName())) {
                    // 把AutoStartup设定的计划任务初始设置为暂停状态
                    if (!jobBeanCfg.getAutoStartup()) {
                        logger.debug("Setup trigger {} state to PAUSE", trigger.getKey().getName());
                        this.getScheduler().pauseTrigger(trigger.getKey());
                    }
                    //设定是否开启日志记录
                    TRIGGER_HIST_MAPPING.put(trigger.getJobKey().getName(), jobBeanCfg.getLogRunHist());
                    break;
                }
            }
        }
    }

    public static boolean isTriggerLogRunHist(Trigger trigger) {
        Boolean hist = TRIGGER_HIST_MAPPING.get(trigger.getJobKey().getName());
        return hist == null ? true : hist;
    }
}

src/main/java/lab/s2jh/module/schedule/web/JobBeanCfgController.java
package lab.s2jh.module.schedule.web;

import javax.servlet.http.HttpServletRequest;

import lab.s2jh.core.annotation.MenuData;
import lab.s2jh.core.service.BaseService;
import lab.s2jh.core.service.Validation;
import lab.s2jh.core.web.BaseController;
import lab.s2jh.core.web.view.OperationResult;
import lab.s2jh.module.schedule.entity.JobBeanCfg;
import lab.s2jh.module.schedule.service.JobBeanCfgService;

import org.apache.shiro.authz.annotation.RequiresPermissions;
import org.apache.shiro.authz.annotation.RequiresUser;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
@RequestMapping(value = "/admin/schedule/job-bean-cfg")
public class JobBeanCfgController extends BaseController<JobBeanCfg, Long> {

    @Autowired
    private JobBeanCfgService jobBeanCfgService;

    @Override
    protected BaseService<JobBeanCfg, Long> getEntityService() {
        return jobBeanCfgService;
    }

    @MenuData("配置管理:计划任务管理:可配置任务管理")
    @RequiresPermissions("配置管理:计划任务管理:可配置任务管理")
    @RequestMapping(value = "", method = RequestMethod.GET)
    public String index() {
        return "admin/schedule/jobBeanCfg-index";
    }

    @RequiresPermissions("配置管理:计划任务管理:可配置任务管理")
    @RequestMapping(value = "/list", method = RequestMethod.GET)
    @ResponseBody
    public Page<JobBeanCfg> findByPage(HttpServletRequest request) {
        return super.findByPage(JobBeanCfg.class, request);
    }

    @RequiresPermissions("配置管理:计划任务管理:可配置任务管理")
    @RequestMapping(value = "/edit", method = RequestMethod.POST)
    @ResponseBody
    public OperationResult editSave(@ModelAttribute("entity") JobBeanCfg entity, HttpServletRequest request) {
        Validation.notDemoMode();
        return super.editSave(entity);
    }

    @RequiresUser
    @ModelAttribute
    public void prepareModel(HttpServletRequest request, Model model, @RequestParam(value = "id", required = false) Long id) {
        super.initPrepareModel(request, model, id);
    }
}

src/main/webapp/WEB-INF/views/admin/schedule/jobBeanCfg-index.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<c:set var="ctx" value="${pageContext.request.contextPath}" />
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>借款列表</title>
</head>
<body>
	<div class="row search-form-default">
		<div class="col-md-12">
			<form method="get" class="form-inline form-validation form-search-init control-label-sm"
				data-grid-search="#grid-schedule-job-bean-cfg-index">
				<div class="form-group">
					<div class="controls controls-clearfix">
						<input type="text" name="search['CN_jobClass_OR_description']" class="form-control input-large"
							placeholder="类名，描述...">
					</div>
				</div>
				<div class="form-group search-group-btn">
					<button class="btn green" type="submmit">
						<i class="m-icon-swapright m-icon-white"></i>&nbsp; 查&nbsp;询
					</button>
					<button class="btn default" type="reset">
						<i class="fa fa-undo"></i>&nbsp; 重&nbsp;置
					</button>
				</div>
			</form>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<table id="grid-schedule-job-bean-cfg-index"></table>
		</div>
	</div>

	<script type="text/javascript">
        $(function() {
            $("#grid-schedule-job-bean-cfg-index").data("gridOptions", {
                url : WEB_ROOT + '/admin/schedule/job-bean-cfg/list',
                colModel : [ {
                    label : '任务类全名',
                    name : 'jobClass',
                    width : 200,
                    editable : true,
                    editoptions : {
                        placeholder : '新添加计划任务不会立刻安排作业,需要重启应用服务器才能生效'
                    }
                }, {
                    label : 'CRON表达式',
                    name : 'cronExpression',
                    width : 100,
                    editable : true,
                    align : 'right'
                }, {
                    label : '自动初始运行',
                    name : 'autoStartup',
                    formatter : 'checkbox',
                    editable : true,
                    editoptions : {
                        title : '是否随应用启动之后自动部署运行任务，禁用后需要手工启动任务运行'
                    }
                }, {
                    label : '启用历史记录',
                    name : 'logRunHist',
                    formatter : 'checkbox',
                    editable : true,
                    editoptions : {
                        title : '关键任务建议启用历史记录，对非关键任务且运行频率较高考虑性能因素建议关闭'
                    }
                }, {
                    label : '集群运行模式',
                    name : 'runWithinCluster',
                    formatter : 'checkbox',
                    editable : true,
                    editoptions : {
                        title : '变更运行模式会移除当前计划任务,并需要重启应用服务器才能生效'
                    }
                }, {
                    label : '名称描述',
                    name : 'description',
                    editable : true,
                    edittype : 'textarea',
                    width : 100,
                    align : 'left'
                } ],
                editurl : WEB_ROOT + "/admin/schedule/job-bean-cfg/edit",
                editrulesurl : WEB_ROOT + '/admin/util/validate?clazz=${clazz}'
            });
        });
    </script>
</body>
</html>

src/main/webapp/WEB-INF/views/admin/schedule/jobRunHist-index.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<c:set var="ctx" value="${pageContext.request.contextPath}" />
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>借款列表</title>
</head>
<body>
	<div class="row search-form-default">
		<div class="col-md-12">
			<form method="get" class="form-inline form-validation form-search-init control-label-sm"
				data-grid-search="#grid-schedule-job-run-hist-index">
				<div class="form-group">
					<div class="controls controls-clearfix">
						<input type="text" name="search['CN_jobName_OR_nodeId']" class="form-control input-large" placeholder="任务名称、主机...">
					</div>
				</div>
				<div class="form-group search-group-btn">
					<button class="btn green" type="submmit">
						<i class="m-icon-swapright m-icon-white"></i>&nbsp; 查&nbsp;询
					</button>
					<button class="btn default" type="reset">
						<i class="fa fa-undo"></i>&nbsp; 重&nbsp;置
					</button>
				</div>
			</form>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<table id="grid-schedule-job-run-hist-index"></table>
		</div>
	</div>

	<script type="text/javascript">
        $(function() {
            $("#grid-schedule-job-run-hist-index").data("gridOptions", {
                url : WEB_ROOT + '/admin/schedule/job-run-hist/list',
                colNames : [ '流水号', '主机节点', '任务名称', '触发时间', '下次触发时间', '触发次数', '异常标识', '执行结果', '创建时间', '版本号' ],
                colModel : [ {
                    name : 'id',
                    align : 'center',
                    width : 50
                }, {
                    name : 'nodeId',
                    width : 150,
                    align : 'center'
                }, {
                    name : 'jobName',
                    width : 200,
                    align : 'left'
                }, {
                    name : 'previousFireTime',
                    fixed : true,
                    sorttype : 'date',
                    align : 'center'
                }, {
                    name : 'nextFireTime',
                    fixed : true,
                    sorttype : 'date',
                    align : 'center'
                }, {
                    name : 'refireCount',
                    width : 60,
                    fixed : true,
                    hidden : true,
                    align : 'right'
                }, {
                    name : 'exceptionFlag',
                    fixed : true,
                    formatter : 'checkbox',
                    align : 'center'
                }, {
                    name : 'result',
                    width : 100,
                    align : 'left'
                }, {
                    name : 'createdDate',
                    width : 120,
                    fixed : true,
                    hidden : true,
                    align : 'center'
                }, {
                    name : 'version',
                    hidden : true,
                    hidedlg : true
                } ],
                multiselect : false,
                viewurl : WEB_ROOT + '/admin/schedule/job-run-hist/view',
                addable : false
            });
        });
    </script>
</body>
</html>

src/main/webapp/WEB-INF/views/admin/schedule/jobRunHist-view.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>运行记录详情</title>
</head>
<body>
	<div class="form-horizontal form-bordered form-label-stripped">
		<div class="form-group">
			<label class="control-label">执行结果</label>
			<div class="controls">
				<pre>${entity.result}</pre>
			</div>
		</div>
		<div class="form-group">
			<label class="control-label">异常标识</label>
			<div class="controls">
				<p class="form-control-static">
					${entity.exceptionFlag}
				</p>
			</div>
		</div>
		<div class="form-group">
			<label class="control-label">异常日志</label>
			<div class="controls">
				<pre>${entity.exceptionStack}</pre>
			</div>
		</div>
	</div>
</body>
</html>

src/main/webapp/WEB-INF/views/admin/schedule/quartzTrigger-index.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<c:set var="ctx" value="${pageContext.request.contextPath}" />
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>定时任务控制</title>
</head>
<body>
	<div class="row">
		<div class="col-md-12">
			<table id="grid-schedule-triggers" data-grid="table"></table>
		</div>
	</div>
	<script type="text/javascript">
        $(function() {
            $("#grid-schedule-triggers").data("gridOptions", {
                url : WEB_ROOT + '/admin/schedule/quartz-trigger/list',
                colNames : [ '任务名称', 'CRON表达式', '当前状态', '上次触发时间', '下次触发时间', '集群运行模式' ],
                colModel : [ {
                    name : 'jobName',
                    width : 240,
                    align : 'left'
                }, {
                    name : 'cronExpression',
                    width : 100,
                    align : 'right'
                }, {
                    name : 'stateLabel',
                    width : 60,
                    align : 'center'
                }, {
                    name : 'previousFireTime',
                    sorttype : 'date',
                    align : 'center'
                }, {
                    name : 'nextFireTime',
                    sorttype : 'date',
                    align : 'center'
                }, {
                    name : 'runWithinCluster',
                    formatter : 'checkbox'
                } ],
                rowNum : -1,
                loadonce : true,
                addable : false,
                loadonce : true,
                operations : function(items) {
                    var $grid = $(this);
                    var $resume = $('<li data-position="multi" data-toolbar="show" data-text="show"><a><i class="fa fa-play"></i> 启动</a></li>');
                    $resume.children("a").bind("click", function(e) {
                        e.preventDefault();
                        var ids = $grid.getAtLeastOneSelectedItem();
                        if (ids) {
                            $grid.ajaxPostURL({
                                url : WEB_ROOT + '/admin/schedule/quartz-trigger/state',
                                success : function() {
                                    $grid.refresh();
                                },
                                confirmMsg : "确认 启动 所选任务？",
                                data : {
                                    ids : ids.join(","),
                                    state : 'resume'
                                }
                            })
                        }
                    });
                    items.push($resume);
                    var $pause = $('<li data-position="multi" data-toolbar="show" data-text="show"><a><i class="fa fa-pause"></i> 暂停</a></li>');
                    $pause.children("a").bind("click", function(e) {
                        e.preventDefault();
                        var ids = $grid.getAtLeastOneSelectedItem();
                        if (ids) {
                            $grid.ajaxPostURL({
                                url : WEB_ROOT + '/admin/schedule/quartz-trigger/state',
                                success : function() {
                                    $grid.refresh();
                                },
                                confirmMsg : "确认 暂停 所选任务？",
                                data : {
                                    ids : ids.join(","),
                                    state : 'pause'
                                }
                            })
                        }
                    });
                    items.push($pause);
                    var $run = $('<li data-position="multi" data-toolbar="show" data-text="show"><a><i class="fa fa-bolt"></i> 立即执行</a></li>');
                    $run.children("a").bind("click", function(e) {
                        e.preventDefault();
                        var ids = $grid.getAtLeastOneSelectedItem();
                        if (ids) {
                            $grid.ajaxPostURL({
                                url : WEB_ROOT + '/admin/schedule/quartz-trigger/run',
                                success : function() {
                                    $grid.refresh();
                                },
                                confirmMsg : "确认 立即执行 所选任务？",
                                data : {
                                    ids : ids.join(",")
                                }
                            })
                        }
                    });
                    items.push($run);
                }
            });
        });
    </script>
</body>
</html>