src/main/java/lab/s2jh/module/sys/entity/NotifyMessage.java
package lab.s2jh.module.sys.entity;

import java.util.Date;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Transient;

import lab.s2jh.core.annotation.MetaData;
import lab.s2jh.core.entity.BaseNativeEntity;
import lab.s2jh.core.util.WebFormatter;
import lab.s2jh.core.web.json.ShortDateTimeJsonSerializer;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;

import org.apache.commons.lang3.StringUtils;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@Getter
@Setter
@Accessors(chain = true)
@Access(AccessType.FIELD)
@Entity
@Table(name = "sys_NotifyMessage")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@MetaData(value = "公告消息")
public class NotifyMessage extends BaseNativeEntity {

    private static final long serialVersionUID = 2544390748513253055L;

    @MetaData(value = "消息类型", comments = "从数据字典定义的消息类型")
    @Column(length = 32, nullable = true)
    private String type;

    @MetaData(value = "标题")
    @Column(length = 128, nullable = false)
    private String title;

    @MetaData(value = "生效标识", comments = "安排定时任务，基于publishTime和expireTime更新此值")
    @Column(nullable = true)
    private Boolean effective;

    @MetaData(value = "标识必须登录才能访问")
    @Column(nullable = false)
    private Boolean authRequired = Boolean.FALSE;

    @MetaData(value = "发布时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
    @Column(nullable = false)
    @JsonSerialize(using = ShortDateTimeJsonSerializer.class)
    private Date publishTime;

    @MetaData(value = "到期时间", comments = "为空表示永不过期")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
    @JsonSerialize(using = ShortDateTimeJsonSerializer.class)
    private Date expireTime;

    @MetaData(value = "平台设置", comments = "没有值=全部，其他为如下几项逗号分隔组合：web-admin,web-site,ios,android,winphone, @see NotifyMessage#NotifyMessagePlatformEnum")
    @Column(length = 200, nullable = true)
    private String platform;

    @MetaData(value = "消息目标属性OR并集", comments = "用标签来进行大规模的设备属性、用户属性分群，各元素之间为OR取并集。没有值=全部，其他为数据字典项逗号分隔组合，如：student, teacher")
    @Column(length = 1000, nullable = true)
    private String audienceTags;

    @MetaData(value = "消息目标属性AND交集", comments = "用标签来进行大规模的设备属性、用户属性分群，各元素之间为AND取交集。没有值=全部，其他为数据字典项逗号分隔组合，如：student, school_01")
    @Column(length = 1000, nullable = true)
    private String audienceAndTags;

    @MetaData(value = "用户标识列表", comments = "User对象的alias列表，各元素之间为OR取并集。没有值=全部，其他为数据字典项逗号分隔组合，如：user_01,user_02")
    @Column(length = 1000, nullable = true)
    private String audienceAlias;

    @MetaData(value = "APP弹出提示内容", comments = "如果不为空则触发APP弹出通知，为空则不会弹出而只会推送应用消息")
    @Column(length = 200)
    private String notification;

    @MetaData(value = "最近推送时间", comments = "为空表示尚未推送过")
    private Date lastPushTime;

    @MetaData(value = "消息内容", comments = "可以是无格式的TEXT或格式化的HTMl，一般是在邮件或WEB页面查看的HTML格式详细内容")
    @Lob
    @Column(nullable = false)
    @JsonIgnore
    private String message;

    @MetaData(value = "总计查看用户数")
    private Integer readUserCount = 0;

    @MetaData(value = "排序号", tooltips = "数字越大显示越靠上")
    private Integer orderRank = 100;

    @MetaData(value = "关联附件个数", comments = "用于列表显示和关联处理附件清理判断")
    private Integer attachmentSize;

    @Transient
    @MetaData(value = "标识已读")
    private Boolean readed;

    public static enum NotifyMessagePlatformEnum {

        @MetaData(value = "后端系统")
        web_admin,

        @MetaData(value = "前端网站")
        web_site,

        @MetaData(value = "移动网站")
        html5_site,

        @MetaData(value = "苹果iOS")
        ios,

        @MetaData(value = "安卓Android")
        android,

        @MetaData(value = "Win Phone")
        winphone;

    }

    @Override
    @Transient
    public String getDisplay() {
        return title;
    }

    @Transient
    public String getMessageAbstract() {
        if (StringUtils.isNotBlank(notification)) {
            return notification;
        } else {
            //优化为提取HTML内容text摘要
            if (!StringUtils.isEmpty(message)) {
                return StringUtils.substring(WebFormatter.html2text(message), 0, 50).trim() + "...";
            } else {
                return "";
            }

        }
    }

    @Transient
    public boolean isPublic() {
        if (StringUtils.isBlank(audienceTags) && StringUtils.isBlank(audienceAndTags) && StringUtils.isBlank(audienceAlias)) {
            return true;
        }
        return false;
    }

    @MetaData(value = "辅助方法：用于表单数据绑定")
    @Transient
    public String[] getPlatformSplit() {
        return StringUtils.isNotBlank(platform) ? platform.split(",") : null;
    }

    @MetaData(value = "辅助方法：用于表单数据绑定")
    @Transient
    public void setPlatformSplit(String[] platformSplit) {
        platform = platformSplit != null ? StringUtils.join(platformSplit, ",") : null;
    }
}

src/main/java/lab/s2jh/module/sys/entity/UserMessage.java
package lab.s2jh.module.sys.entity;

import java.util.Date;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import lab.s2jh.core.annotation.MetaData;
import lab.s2jh.core.entity.BaseNativeEntity;
import lab.s2jh.core.util.WebFormatter;
import lab.s2jh.core.web.json.DateTimeJsonSerializer;
import lab.s2jh.core.web.json.EntityIdDisplaySerializer;
import lab.s2jh.core.web.json.JsonViews;
import lab.s2jh.module.auth.entity.User;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;

import org.apache.commons.lang3.StringUtils;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import com.fasterxml.jackson.annotation.JsonView;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@Getter
@Setter
@Accessors(chain = true)
@Access(AccessType.FIELD)
@Entity
@Table(name = "sys_UserMessage")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@MetaData(value = "用户消息", comments = "如果用户消息量担心影响查询效率，可以考虑引入定期归档处理把过期消息搬迁归档")
public class UserMessage extends BaseNativeEntity {

    private static final long serialVersionUID = 1685596718660284598L;

    @MetaData(value = "消息类型", comments = "从数据字典定义的消息类型")
    @Column(length = 32, nullable = true)
    private String type;

    @MetaData(value = "标题")
    @Column(nullable = false)
    private String title;

    @MetaData(value = "目标用户")
    @ManyToOne
    @JoinColumn(name = "targetUser_id", nullable = false)
    @JsonSerialize(using = EntityIdDisplaySerializer.class)
    @JsonView(JsonViews.Admin.class)
    private User targetUser;

    @MetaData(value = "邮件推送消息")
    @JsonView(JsonViews.Admin.class)
    private Boolean emailPush = Boolean.FALSE;

    @MetaData(value = "邮件推送消息时间", comments = "为空表示尚未推送过")
    @JsonView(JsonViews.Admin.class)
    private Date emailPushTime;

    @MetaData(value = "短信推送消息")
    @JsonView(JsonViews.Admin.class)
    private Boolean smsPush = Boolean.FALSE;

    @MetaData(value = "短信推送消息时间", comments = "为空表示尚未推送过")
    @JsonView(JsonViews.Admin.class)
    private Date smsPushTime;

    @MetaData(value = "APP推送消息")
    @JsonView(JsonViews.Admin.class)
    private Boolean appPush = Boolean.FALSE;

    @MetaData(value = "APP推送消息时间", comments = "为空表示尚未推送过")
    @JsonView(JsonViews.Admin.class)
    private Date appPushTime;

    @MetaData(value = "APP弹出提示内容", comments = "如果不为空则触发APP弹出通知，为空则不会弹出而只会推送应用消息")
    @Column(length = 200)
    @JsonView(JsonViews.Admin.class)
    private String notification;

    @MetaData(value = "消息内容", comments = "可以是无格式的TEXT或格式化的HTMl，一般是在邮件或WEB页面查看的HTML格式详细内容")
    @Lob
    @Column(nullable = false)
    private String message;

    @MetaData(value = "关联附件个数", comments = "用于列表显示和关联处理附件清理判断")
    @JsonView(JsonViews.Admin.class)
    private Integer attachmentSize;

    @MetaData(value = "首次阅读时间")
    @JsonSerialize(using = DateTimeJsonSerializer.class)
    @JsonView(JsonViews.Admin.class)
    private Date firstReadTime;

    @MetaData(value = "最后阅读时间")
    @JsonSerialize(using = DateTimeJsonSerializer.class)
    @JsonView(JsonViews.Admin.class)
    private Date lastReadTime;

    @MetaData(value = "总计阅读次数")
    @Column(nullable = false)
    private Integer readTotalCount = 0;

    @Override
    @Transient
    public String getDisplay() {
        return title;
    }

    @Transient
    @JsonView(JsonViews.Admin.class)
    public String getMessageAbstract() {
        if (StringUtils.isNotBlank(notification)) {
            return notification;
        } else {
            //优化为提取HTML内容text摘要
            if (!StringUtils.isEmpty(message)) {
                return StringUtils.substring(WebFormatter.html2text(message), 0, 50).trim() + "...";
            } else {
                return "";
            }
        }
    }
}

src/main/java/lab/s2jh/module/sys/web/NotifyMessageController.java
package lab.s2jh.module.sys.web;

import java.text.SimpleDateFormat;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;

import lab.s2jh.core.annotation.MenuData;
import lab.s2jh.core.pagination.GroupPropertyFilter;
import lab.s2jh.core.pagination.PropertyFilter;
import lab.s2jh.core.service.BaseService;
import lab.s2jh.core.service.Validation;
import lab.s2jh.core.util.DateUtils;
import lab.s2jh.core.util.EnumUtils;
import lab.s2jh.core.web.BaseController;
import lab.s2jh.core.web.view.OperationResult;
import lab.s2jh.module.sys.entity.NotifyMessage;
import lab.s2jh.module.sys.entity.NotifyMessage.NotifyMessagePlatformEnum;
import lab.s2jh.module.sys.entity.NotifyMessageRead;
import lab.s2jh.module.sys.service.NotifyMessageReadService;
import lab.s2jh.module.sys.service.NotifyMessageService;

import org.apache.shiro.authz.annotation.RequiresPermissions;
import org.apache.shiro.authz.annotation.RequiresUser;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.propertyeditors.CustomDateEditor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.WebDataBinder;
import org.springframework.web.bind.annotation.InitBinder;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
@RequestMapping(value = "/admin/sys/notify-message")
public class NotifyMessageController extends BaseController<NotifyMessage, Long> {

    @Autowired
    private NotifyMessageService notifyMessageService;

    @Autowired
    private NotifyMessageReadService notifyMessageReadService;

    @Override
    protected BaseService<NotifyMessage, Long> getEntityService() {
        return notifyMessageService;
    }

    @InitBinder
    protected void initBinder(WebDataBinder binder) {
        super.initBinder(binder);
        binder.registerCustomEditor(Date.class, "publishTime", new CustomDateEditor(new SimpleDateFormat(DateUtils.SHORT_TIME_FORMAT), true));
        binder.registerCustomEditor(Date.class, "expireTime", new CustomDateEditor(new SimpleDateFormat(DateUtils.SHORT_TIME_FORMAT), true));
    }

    @RequiresUser
    @ModelAttribute
    public void prepareModel(HttpServletRequest request, Model model, @RequestParam(value = "id", required = false) Long id) {
        super.initPrepareModel(request, model, id);
    }

    @MenuData("配置管理:系统管理:公告管理")
    @RequiresPermissions("配置管理:系统管理:公告管理")
    @RequestMapping(value = "", method = RequestMethod.GET)
    public String index(Model model) {
        return "admin/sys/notifyMessage-index";
    }

    @RequiresPermissions("配置管理:系统管理:公告管理")
    @RequestMapping(value = "/list", method = RequestMethod.GET)
    @ResponseBody
    public Page<NotifyMessage> findByPage(HttpServletRequest request) {
        return super.findByPage(NotifyMessage.class, request);
    }

    @RequiresPermissions("配置管理:系统管理:公告管理")
    @RequestMapping(value = "/edit", method = RequestMethod.GET)
    public String editShow(Model model) {
        model.addAttribute("platformMap", EnumUtils.getEnumDataMap(NotifyMessagePlatformEnum.class));
        return "admin/sys/notifyMessage-inputBasic";
    }

    @RequiresPermissions("配置管理:系统管理:公告管理")
    @RequestMapping(value = "/edit", method = RequestMethod.POST)
    @ResponseBody
    public OperationResult editSave(@ModelAttribute("entity") NotifyMessage entity, Model model) {
        return super.editSave(entity);
    }

    @RequiresPermissions("配置管理:系统管理:公告管理")
    @RequestMapping(value = "/delete", method = RequestMethod.POST)
    @ResponseBody
    public OperationResult delete(@ModelAttribute("entity") NotifyMessage entity, Model model) {
        Integer readCount = notifyMessageReadService.countByNotifyMessage(entity);
        Validation.isTrue(readCount <= 0, "该公告已经被阅读，不能被删除");
        notifyMessageService.delete(entity);
        return OperationResult.buildSuccessResult();
    }

    @RequiresPermissions("配置管理:系统管理:公告管理")
    @RequestMapping(value = "/read-list", method = RequestMethod.GET)
    @ResponseBody
    public Page<NotifyMessageRead> readList(HttpServletRequest request) {
        Pageable pageable = PropertyFilter.buildPageableFromHttpRequest(request);
        GroupPropertyFilter groupFilter = GroupPropertyFilter.buildFromHttpRequest(NotifyMessageRead.class, request);
        return notifyMessageReadService.findByPage(groupFilter, pageable);
    }

}

src/main/java/lab/s2jh/module/sys/web/UserMessageController.java
package lab.s2jh.module.sys.web;

import javax.servlet.http.HttpServletRequest;

import lab.s2jh.core.annotation.MenuData;
import lab.s2jh.core.service.BaseService;
import lab.s2jh.core.web.BaseController;
import lab.s2jh.module.sys.entity.UserMessage;
import lab.s2jh.module.sys.service.UserMessageService;

import org.apache.shiro.authz.annotation.RequiresPermissions;
import org.apache.shiro.authz.annotation.RequiresUser;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
@RequestMapping(value = "/admin/sys/user-message")
public class UserMessageController extends BaseController<UserMessage, Long> {

    @Autowired
    private UserMessageService userMessageService;

    @Override
    protected BaseService<UserMessage, Long> getEntityService() {
        return userMessageService;
    }

    @RequiresUser
    @ModelAttribute
    public void prepareModel(HttpServletRequest request, Model model, @RequestParam(value = "id", required = false) Long id) {
        super.initPrepareModel(request, model, id);
    }

    @MenuData("配置管理:系统管理:消息管理")
    @RequiresPermissions("配置管理:系统管理:消息管理")
    @RequestMapping(value = "", method = RequestMethod.GET)
    public String index(Model model) {
        return "admin/sys/userMessage-index";
    }

    @RequiresPermissions("配置管理:系统管理:消息管理")
    @RequestMapping(value = "/list", method = RequestMethod.GET)
    @ResponseBody
    public Page<UserMessage> findByPage(HttpServletRequest request) {
        return super.findByPage(UserMessage.class, request);
    }

    @RequiresPermissions("配置管理:系统管理:消息管理")
    @RequestMapping(value = "/edit", method = RequestMethod.GET)
    public String editShow(Model model) {
        return "admin/sys/userMessage-inputBasic";
    }
}

src/main/webapp/WEB-INF/views/admin/profile/credentials-expire.jsp
<%@ page contentType="text/html;charset=UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="tags" tagdir="/WEB-INF/tags"%>
<c:set var="ctx" value="${pageContext.request.contextPath}" />
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta content="/WEB-INF/views/layouts/admin-login.jsp" name="decorator" />
<title>请重置密码</title>
</head>
<body>
	<div class="row">
		<div class="col-md-12">
			<form class="form-horizontal form-bordered form-validation" method="post"
				action="${ctx}/admin/profile/credentials-expire" data-editrulesurl="false">
				<h3 class="form-title" style="color: #666666">请重置密码</h3>
				<div class="note note-info">
					<p>系统检测您是首次或长期未修改密码，为了您的账户安全，请重置修改您的登录密码。</p>
					<p>请注意：系统会根据规则对新密码进行强度校验，例如包括但不限于'不能等于上次密码'等规则。</p>
				</div>
				<div class="form-body">
					<div class="form-group">
						<label class="control-label">输入新密码</label>
						<div class="controls">
							<input type="password" name="newpasswd" class="form-control" required="true">
						</div>
					</div>
					<div class="form-group">
						<label class="control-label">确认新密码</label>
						<div class="controls">
							<input type="password" name="cfmpasswd" class="form-control" required="true" data-rule-equalToByName="newpasswd">
						</div>
					</div>
				</div>
				<div class="form-actions right">
					<button class="btn blue" type="submit" data-post-dismiss="modal">提 交</button>
				</div>
			</form>
		</div>
	</div>
</body>
</html>

src/main/webapp/WEB-INF/views/admin/profile/notifyMessage-index.jsp
<%@ page contentType="text/html;charset=UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<c:set var="ctx" value="${pageContext.request.contextPath}" />
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<body>
	<div class="row search-form-default">
		<div class="col-md-12">
			<form action="${ctx}/admin/profile/notify-message-list?readed=${param.readed}" method="get"
				class="form-inline form-validation form-search-init control-label-sm"
				data-div-search=".profile-notify-message-List">
				<div class="btn-group">
					<a class="btn btn-default ${empty param.readed?'active':''}" href='javascripts:;'
						rel='address:/admin/profile/notify-message|公告信息列表'>全部</a><a
						class="btn btn-default ${param.readed=='no'?'active':''}" href='javascripts:;'
						rel='address:/admin/profile/notify-message?readed=no|未读公告信息列表'>未读</a><a
						class="btn btn-default ${param.readed=='yes'?'active':''}" href='javascripts:;'
						rel='address:/admin/profile/notify-message?readed=yes|已读公告信息列表'>已读</a>
				</div>
				<div class="form-group search-group-btn hide">
					<button class="btn green" type="submmit">
						<i class="m-icon-swapright m-icon-white"></i>&nbsp; 查&nbsp;询
					</button>
					<button class="btn default" type="reset">
						<i class="fa fa-undo"></i>&nbsp; 重&nbsp;置
					</button>
				</div>

			</form>
		</div>
	</div>

	<div class="profile-notify-message-List"></div>
</body>
</html>

src/main/webapp/WEB-INF/views/admin/profile/notifyMessage-list.jsp
<%@ page contentType="text/html;charset=UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="tags" tagdir="/WEB-INF/tags"%>
<c:set var="ctx" value="${pageContext.request.contextPath}" />
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>通知消息列表</title>
</head>
<body>
	<div class="row">
		<div class="col-md-12">
			<table class="table table-striped table-hover table-bordered">
				<thead>
					<tr>
						<th>消息标题</th>
						<th>消息摘要</th>
						<th>发布时间</th>
					</tr>
				</thead>
				<tbody>
					<c:forEach var="item" items="${notifyMessages}">
						<tr>
							<td><a href="${ctx}/admin/profile/notify-message-view/${item.id}" data-toggle="modal-ajaxify" title="查看消息">
									<c:if test="${!item.readed}">
										<i class="fa fa-envelope-o"></i>
									</c:if> ${item.title}
							</a></td>
							<td>${item.messageAbstract}</td>
							<td><fmt:formatDate value="${item.publishTime}" type="both" pattern="yyyy-MM-dd mm:HH:ss" /></td>
						</tr>
					</c:forEach>
				</tbody>
			</table>
		</div>
	</div>
</body>
</html>

src/main/webapp/WEB-INF/views/admin/profile/notifyMessage-view.jsp
<%@ page contentType="text/html;charset=UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="tags" tagdir="/WEB-INF/tags"%>
<c:set var="ctx" value="${pageContext.request.contextPath}" />
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>通知消息查看</title>
</head>
<body>
	<div class="form-horizontal">
		<div class="form-body">
			<h3 class="margin-bottom-20">${notifyMessage.title}</h3>
			<div class="row">
				<div class="col-md-12">
					${notifyMessage.message}
				</div>
			</div>
		</div>
	</div>
</body>
</html>

src/main/webapp/WEB-INF/views/admin/profile/userMessage-list.jsp
<%@ page contentType="text/html;charset=UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="tags" tagdir="/WEB-INF/tags"%>
<c:set var="ctx" value="${pageContext.request.contextPath}" />
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
</head>
<body>
	<div class="row">
		<div class="col-md-12">
			<table class="table table-striped table-hover table-bordered">
				<thead>
					<tr>
						<th>消息标题</th>
						<th>消息摘要</th>
						<th>发布时间</th>
					</tr>
				</thead>
				<tbody>
					<c:forEach var="item" items="${pageData.content}">
						<tr>
							<td><a href="${ctx}/admin/profile/user-message-view/${item.id}" data-toggle="modal-ajaxify" title="查看消息">
									<c:if test="${item.lastReadTime==null}">
										<i class="fa fa-envelope-o"></i>
									</c:if> ${item.title}
							</a></td>
							<td>${item.messageAbstract}</td>
							<td><fmt:formatDate value="${item.createdDate}" type="both" pattern="yyyy-MM-dd mm:HH:ss" /></td>
						</tr>
					</c:forEach>
				</tbody>
			</table>
			<tags:pagination page="${pageData}" />
		</div>
	</div>
</body>
</html>

src/main/webapp/WEB-INF/views/admin/profile/userMessage-view.jsp
<%@ page contentType="text/html;charset=UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="tags" tagdir="/WEB-INF/tags"%>
<c:set var="ctx" value="${pageContext.request.contextPath}" />
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>通知消息查看</title>
</head>
<body>
	<div class="form-horizontal">
		<div class="form-body">
			<h3 class="margin-bottom-20">${notifyMessage.title}</h3>
			<div class="row">
				<div class="col-md-12">
					${notifyMessage.message}
				</div>
			</div>
		</div>
	</div>
</body>
</html>